services:
  php:
    image: drewviles/php-pdo:latest # in real life we should create our own Dockerfile and used for dev and prod. This is just to speed up.
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  composer:
    image: composer:2
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - php

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
