services:
  php:
    image: drewviles/php-pdo:latest # in real life we should create our own Dockerfile for dev and prod, never use ":latest", etc. This is just to speed up.
    volumes:
      - .:/app
    working_dir: /app
    command: php-fpm
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"

  composer:
    image: composer:2
    volumes:
      - .:/app
    working_dir: /app
    profiles:
      - donotstart

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"

  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
