services:
  php:
    image: php:8.4-cli
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=test
      - DB_USERNAME=root
      - DB_PASSWORD=root
    extra_hosts:
      - "host.docker.internal:host-gateway"

  composer:
    image: composer:2
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - php

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
